### ISSUE TITLE
Bug: notifications keep disapearing

### ISSUE THREAD

**Issue by Nokel81** [gitify-app/gitify#482] opened 2021-01-25 13:16 UTC
### Platform:
Version: v4.1.0
OS: macOS 10.15

### Description:
If I open the gitify notification viewer and click on a notification then it opens (and subsequently closes the tray viewer). However, if I then go back to the viewer all but one notification are no longer present (there are ~6). If I then press the reload button all the notifications come back.

### Images:
Here is a screenshot of my settings:
<img width="429" alt="Screen Shot 2021-01-25 at 8 16 25 AM" src="https://user-images.githubusercontent.com/8225332/105710812-9f6a5600-5ee5-11eb-8eb1-015623cf68c8.png">

I have gitify connected to my github public account.

**Comment by bquorning** [comment] 2021-03-03 13:42
@manosim I am not sure if you have seen this bug report. Do you need more details? I run into this problem almost _every_ time I click a notification – next time I open Gitify (1 second later) half of the notifications don't appear anymore. However if I force a reload (arrow button) or wait until Gitify syncs by itself, the notifications reappear (except the one I clicked).

Sounds like a caching issue to me.

**Comment by afonsojramos** [comment] 2023-09-25 23:29
Closing for now, feel free to ping if it is still happening!

**Comment by bquorning** [comment] 2023-10-06 12:07
This issue is still occurring on Gitify v4.4.0.

**Comment by afonsojramos** [comment] 2023-10-10 23:47
@bquorning is it not #624?

**Comment by bquorning** [comment] 2023-10-11 05:44
> @bquorning is it not https://github.com/gitify-app/gitify/issues/624?

No, they’re not the same issue.

I do see notifications in Gitify, but (sometimes) when I click on one, the next time I open Gitify (a second later) there are no notifications. When I refresh, the notifications show up again.

(These are GitHub notifications by the way, not OS notifications)

**Comment by bmulholland** [comment] 2023-10-11 06:24
Yeah, it’s some sort of weird caching issue. I’ve seen it too. There’s an easy workaround though, as you say. Just click refresh. For that reason this isn’t as high priorities as other issues.

**Comment by bquorning** [comment] 2024-03-12 09:27
This issue is still occurring on Gitify v4.5.1.
macOS 13.6.3.

Is there anything I can do to help solve this issue? Can I enable logging or some other debugging output?

**Comment by bmulholland** [comment] 2024-03-18 11:27
The current maintainers have all taken over this project relatively recently, so solving it is almost as long for us as it would be for you. If it's bothering you enough, then dig in to the code :)

For now, we're all focused on bringing things up to date, getting code signing working again, and so forth.

**Comment by bquorning** [comment] 2024-03-18 13:27
And don’t get me wrong: your work is very much appreciated ❤️ 

I just wanted to keep this issue updated, so it’s not suddenly closed down by a bot (not sure if there’s a “stale-bot” running in this repo though).

**Comment by setchy** [comment] 2024-05-01 17:08
@bquorning - would you mind validating if this is now resolved.  I'm hopeful your issues were resolved as part of this fix  https://github.com/gitify-app/gitify/pull/1037

**Comment by setchy** [comment] 2024-05-02 16:01
Closing as 5.4.0 should have resolved this :)

**Closed by setchy** 2024-05-02 16:01 UTC
Labels: bug

**Comment by bquorning** [comment] 2024-05-07 08:47
Indeed, it seems like the problem is gone as of v5.4.0. Thank you ❤️
