### ISSUE TITLE
[Questions] More than one account, and dark background option?

### ISSUE THREAD

**Issue by MostHated** [gitify-app/gitify#414] opened 2020-06-05 04:55 UTC
Hey there,
    I saw that the description mentioned the ability to add multiple accounts, but I am not seeing how to do this, unless by multiple accounts it just means you can have one standard github account and one enterprise account? When I add my account, I only see the option to add an enterprise account. 

Is there any possibility that an option to have a dark background with light/medium grey text could be considered in addition to the white bg with black text?

Thanks,
-MH

**Comment by setchy** [comment] 2024-02-23 21:40
Closing as duplicate of #431

**Closed by setchy** 2024-02-23 21:40 UTC
