### ISSUE TITLE
Clicking on a notification navigates to the repository instead of the issue/pull request/etc.

### ISSUE THREAD

**Issue by axelrindle** [gitify-app/gitify#1656] opened 2024-12-05 10:42 UTC
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

While the notifications per se are working fine, navigating to the source of the notification does not. Clicking on a notification immediately removes it from the list and brings me to the main repository page instead of the issue/pull request/etc.

### 🪜 Steps To Reproduce

1. Receive a notification, e.g. be mentioned in an issue
2. Click on the notification in gitify
3. Land on the main repository page

### Gitify Version

5.16.2

### Operating System

macOS

### GitHub Account

GitHub Cloud

**Comment by setchy** [comment] 2024-12-05 11:25
Likely duplicate of #1645

Can you please check the logs to see where it is failing

**Comment by setchy** [comment] 2024-12-22 06:51
Thanks @JakobEdding - I agree, this is a different issue you and @axelrindle are facing.

Does this happen for all notification types, or only a subset?  

Gitify has a chain of different logic to find the most specific URL to launch.  Based on the error log excerpt above, this is throwing an exception and falling back to our default case (opening the repository root)

To further triage, I'd recommend running Gitify from source and debugging where within the following it is throwing the exception. 

https://github.com/gitify-app/gitify/blob/a34087bbace8c4b0e8a9a4f758c8e48ecad40d7a/src/renderer/utils/helpers.ts#L121-L180

I'll also look separately into adding more details to the error logs for future

**Comment by JakobEdding** [comment] 2024-12-23 07:55
Thanks for your help! I just noticed in the FAQs what scopes Gitify requires the PAT to have. I reused an older PAT that only had the notification's scope enabled and nothing else. I extended the permissions now and everything works fine as expected.

**Comment by setchy** [comment] 2024-12-23 08:08
Great to hear @JakobEdding 🥳 

@axelrindle - perhaps this is also the same for your situation 🤞

**Comment by setchy** [comment] 2024-12-25 07:30
Raised #1685 to help proactively notify users of mismatched scopes

For now I'll be closing this issue.  Happy to reopen if there are other causes to triage.

**Closed** 2024-12-26 08:26 UTC
Labels: bug, host:github-cloud
