### ISSUE TITLE
bug: Windows github login issues

### ISSUE THREAD

**Issue by rladngus133** [gitify-app/gitify#867] opened 2024-03-08 00:30 UTC
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

The ' `Login to github` ' button does not work when running on Windows. (The behavior of the other buttons will work as normal)

### 🪜 Steps To Reproduce

1. Go to https://www.gitify.io/
2. Download and run
3. Clicking the `Login to github` button doesn't work either.

### ℹ System Info

```Markdown
editon : Windows 11 Pro
ver : 22H2
Os build : 22621.3155

Windows Feature Experience Pack 1000.22684.1000.0
```

### 📸 Screenshots

https://github.com/gitify-app/gitify/assets/124851297/74017e2d-fb6d-4f19-ba6c-960b0474a219

**Comment by rladngus133** [comment] 2024-03-08 15:02
I've tried running as administrator, rebooting Windows to resolve the issue, but the symptoms are the same.

**Comment by rladngus133** [comment] 2024-03-08 15:08
This issue is probably related to issue #747

**Comment by Vortigern-The-Grey** [comment] 2024-03-14 06:16
I too have encountered this issue trying out gitfy. Would love to see it resolved.

**Comment by setchy** [comment] 2024-04-02 22:39
This is a duplicate of #747 and requires a rewrite of the OAuth logic. 

For the time being, please use a personal access token.

**Closed** 2024-04-02 22:39 UTC
Labels: bug, platform-windows
